title: Ritik Sinha
logo: /assets/img/ritikPicture.jpg
email: ritiksinha1@gmail.com
description: Studying CS @ UC Berkeley - Passionate about CS, ML, and Education!
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: dark
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/ritik-sinha/
  - name: Resume
    icon: <i class="fa-solid fa-file-lines"></i>
    link: https://drive.google.com/file/d/1wfZ4ArC6lkkII-bO3Xml2nK-fDl0tCK8/view?usp=sharing
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/ritiksinha1

  
  

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
